# Generated by Django 5.0.4 on 2024-04-09 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interval_in_hours', models.IntegerField(null=True)),
                ('interval_in_minutes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RatingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rating_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('review_count', models.PositiveIntegerField()),
                ('link_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.linksetting')),
            ],
        ),
    ]
